# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Search(object):
    def setupUi(self, Search):
        Search.setObjectName("Search")
        Search.resize(969, 934)
        # 固定界面大小尺寸，不能进行缩放
        Search.setWindowFlags(QtCore.Qt.MSWindowsFixedSizeDialogHint)
        self.btn_previous_step = QtWidgets.QPushButton(Search)
        self.btn_previous_step.setGeometry(QtCore.QRect(420, 810, 101, 41))
        self.btn_previous_step.setObjectName("btn_previous_step")
        self.btn_play = QtWidgets.QPushButton(Search)
        self.btn_play.setGeometry(QtCore.QRect(540, 860, 101, 41))
        self.btn_play.setObjectName("btn_play")
        self.label_frame_rate = QtWidgets.QLabel(Search)
        self.label_frame_rate.setGeometry(QtCore.QRect(360, 860, 101, 51))
        self.label_frame_rate.setObjectName("label_frame_rate")
        self.label_initial_state = QtWidgets.QLabel(Search)
        self.label_initial_state.setGeometry(QtCore.QRect(120, 30, 101, 51))
        self.label_initial_state.setObjectName("label_initial_state")
        self.label_algorithm = QtWidgets.QLabel(Search)
        self.label_algorithm.setGeometry(QtCore.QRect(120, 100, 101, 51))
        self.label_algorithm.setObjectName("label_algorithm")
        self.comboBox_algorithm = QtWidgets.QComboBox(Search)
        self.comboBox_algorithm.setGeometry(QtCore.QRect(210, 100, 201, 41))
        self.comboBox_algorithm.setObjectName("comboBox_algorithm")
        self.btn_next_step = QtWidgets.QPushButton(Search)
        self.btn_next_step.setGeometry(QtCore.QRect(540, 810, 101, 41))
        self.btn_next_step.setObjectName("btn_next_step")
        self.btn_start = QtWidgets.QPushButton(Search)
        self.btn_start.setGeometry(QtCore.QRect(750, 810, 121, 41))
        self.btn_start.setObjectName("btn_start")
        self.lineEdit_initial_state = QtWidgets.QLineEdit(Search)
        self.lineEdit_initial_state.setGeometry(QtCore.QRect(210, 30, 201, 41))
        self.lineEdit_initial_state.setObjectName("lineEdit_initial_state")
        self.label_target = QtWidgets.QLabel(Search)
        self.label_target.setGeometry(QtCore.QRect(450, 30, 101, 51))
        self.label_target.setObjectName("label_target")
        self.btn_formatting = QtWidgets.QPushButton(Search)
        self.btn_formatting.setGeometry(QtCore.QRect(750, 860, 121, 41))
        self.btn_formatting.setObjectName("btn_formatting")
        self.lineEdit_target = QtWidgets.QLineEdit(Search)
        self.lineEdit_target.setGeometry(QtCore.QRect(540, 30, 201, 41))
        self.lineEdit_target.setObjectName("lineEdit_target")
        self.comboBox_frame_rate = QtWidgets.QComboBox(Search)
        self.comboBox_frame_rate.setGeometry(QtCore.QRect(420, 860, 101, 41))
        self.comboBox_frame_rate.setObjectName("comboBox_frame_rate")
        self.label_c_node = QtWidgets.QLabel(Search)
        self.label_c_node.setGeometry(QtCore.QRect(80, 340, 101, 51))
        self.label_c_node.setObjectName("label_c_node")
        self.label_c_num = QtWidgets.QLabel(Search)
        self.label_c_num.setGeometry(QtCore.QRect(50, 420, 141, 51))
        self.label_c_num.setObjectName("label_c_num")
        self.btn_show_c_num = QtWidgets.QPushButton(Search)
        self.btn_show_c_num.setGeometry(QtCore.QRect(170, 400, 61, 61))
        self.btn_show_c_num.setText("")
        self.btn_show_c_num.setObjectName("btn_show_c_num")
        self.btn_show_b_1_8 = QtWidgets.QPushButton(Search)
        self.btn_show_b_1_8.setGeometry(QtCore.QRect(510, 390, 41, 41))
        self.btn_show_b_1_8.setText("")
        self.btn_show_b_1_8.setObjectName("btn_show_b_1_8")
        self.btn_show_b_1_9 = QtWidgets.QPushButton(Search)
        self.btn_show_b_1_9.setGeometry(QtCore.QRect(550, 390, 41, 41))
        self.btn_show_b_1_9.setText("")
        self.btn_show_b_1_9.setObjectName("btn_show_b_1_9")
        self.btn_show_b_1_1 = QtWidgets.QPushButton(Search)
        self.btn_show_b_1_1.setGeometry(QtCore.QRect(470, 310, 41, 41))
        self.btn_show_b_1_1.setText("")
        self.btn_show_b_1_1.setObjectName("btn_show_b_1_1")
        self.btn_show_b_1_2 = QtWidgets.QPushButton(Search)
        self.btn_show_b_1_2.setGeometry(QtCore.QRect(510, 310, 41, 41))
        self.btn_show_b_1_2.setText("")
        self.btn_show_b_1_2.setObjectName("btn_show_b_1_2")
        self.btn_show_b_1_4 = QtWidgets.QPushButton(Search)
        self.btn_show_b_1_4.setGeometry(QtCore.QRect(470, 350, 41, 41))
        self.btn_show_b_1_4.setText("")
        self.btn_show_b_1_4.setObjectName("btn_show_b_1_4")
        self.btn_show_b_1_7 = QtWidgets.QPushButton(Search)
        self.btn_show_b_1_7.setGeometry(QtCore.QRect(470, 390, 41, 41))
        self.btn_show_b_1_7.setText("")
        self.btn_show_b_1_7.setObjectName("btn_show_b_1_7")
        self.label_b_node = QtWidgets.QLabel(Search)
        self.label_b_node.setGeometry(QtCore.QRect(380, 390, 101, 51))
        self.label_b_node.setObjectName("label_b_node")
        self.btn_show_b_1_5 = QtWidgets.QPushButton(Search)
        self.btn_show_b_1_5.setGeometry(QtCore.QRect(510, 350, 41, 41))
        self.btn_show_b_1_5.setText("")
        self.btn_show_b_1_5.setObjectName("btn_show_b_1_5")
        self.btn_show_b_1_6 = QtWidgets.QPushButton(Search)
        self.btn_show_b_1_6.setGeometry(QtCore.QRect(550, 350, 41, 41))
        self.btn_show_b_1_6.setText("")
        self.btn_show_b_1_6.setObjectName("btn_show_b_1_6")
        self.btn_show_b_1_num = QtWidgets.QPushButton(Search)
        self.btn_show_b_1_num.setGeometry(QtCore.QRect(470, 440, 51, 41))
        self.btn_show_b_1_num.setText("")
        self.btn_show_b_1_num.setObjectName("btn_show_b_1_num")
        self.btn_show_b_1_3 = QtWidgets.QPushButton(Search)
        self.btn_show_b_1_3.setGeometry(QtCore.QRect(550, 310, 41, 41))
        self.btn_show_b_1_3.setText("")
        self.btn_show_b_1_3.setObjectName("btn_show_b_1_3")
        self.label_b_num = QtWidgets.QLabel(Search)
        self.label_b_num.setGeometry(QtCore.QRect(350, 440, 121, 51))
        self.label_b_num.setObjectName("label_b_num")
        self.btn_show_b_2_7 = QtWidgets.QPushButton(Search)
        self.btn_show_b_2_7.setGeometry(QtCore.QRect(620, 390, 41, 41))
        self.btn_show_b_2_7.setText("")
        self.btn_show_b_2_7.setObjectName("btn_show_b_2_7")
        self.btn_show_b_2_1 = QtWidgets.QPushButton(Search)
        self.btn_show_b_2_1.setGeometry(QtCore.QRect(620, 310, 41, 41))
        self.btn_show_b_2_1.setText("")
        self.btn_show_b_2_1.setObjectName("btn_show_b_2_1")
        self.btn_show_b_2_3 = QtWidgets.QPushButton(Search)
        self.btn_show_b_2_3.setGeometry(QtCore.QRect(700, 310, 41, 41))
        self.btn_show_b_2_3.setText("")
        self.btn_show_b_2_3.setObjectName("btn_show_b_2_3")
        self.btn_show_b_2_9 = QtWidgets.QPushButton(Search)
        self.btn_show_b_2_9.setGeometry(QtCore.QRect(700, 390, 41, 41))
        self.btn_show_b_2_9.setText("")
        self.btn_show_b_2_9.setObjectName("btn_show_b_2_9")
        self.btn_show_b_2_2 = QtWidgets.QPushButton(Search)
        self.btn_show_b_2_2.setGeometry(QtCore.QRect(660, 310, 41, 41))
        self.btn_show_b_2_2.setText("")
        self.btn_show_b_2_2.setObjectName("btn_show_b_2_2")
        self.btn_show_b_2_num = QtWidgets.QPushButton(Search)
        self.btn_show_b_2_num.setGeometry(QtCore.QRect(620, 440, 51, 41))
        self.btn_show_b_2_num.setText("")
        self.btn_show_b_2_num.setObjectName("btn_show_b_2_num")
        self.btn_show_b_2_5 = QtWidgets.QPushButton(Search)
        self.btn_show_b_2_5.setGeometry(QtCore.QRect(660, 350, 41, 41))
        self.btn_show_b_2_5.setText("")
        self.btn_show_b_2_5.setObjectName("btn_show_b_2_5")
        self.btn_show_b_2_4 = QtWidgets.QPushButton(Search)
        self.btn_show_b_2_4.setGeometry(QtCore.QRect(620, 350, 41, 41))
        self.btn_show_b_2_4.setText("")
        self.btn_show_b_2_4.setObjectName("btn_show_b_2_4")
        self.btn_show_b_2_6 = QtWidgets.QPushButton(Search)
        self.btn_show_b_2_6.setGeometry(QtCore.QRect(700, 350, 41, 41))
        self.btn_show_b_2_6.setText("")
        self.btn_show_b_2_6.setObjectName("btn_show_b_2_6")
        self.btn_show_b_2_8 = QtWidgets.QPushButton(Search)
        self.btn_show_b_2_8.setGeometry(QtCore.QRect(660, 390, 41, 41))
        self.btn_show_b_2_8.setText("")
        self.btn_show_b_2_8.setObjectName("btn_show_b_2_8")
        self.btn_show_b_3_7 = QtWidgets.QPushButton(Search)
        self.btn_show_b_3_7.setGeometry(QtCore.QRect(770, 390, 41, 41))
        self.btn_show_b_3_7.setText("")
        self.btn_show_b_3_7.setObjectName("btn_show_b_3_7")
        self.btn_show_b_3_1 = QtWidgets.QPushButton(Search)
        self.btn_show_b_3_1.setGeometry(QtCore.QRect(770, 310, 41, 41))
        self.btn_show_b_3_1.setText("")
        self.btn_show_b_3_1.setObjectName("btn_show_b_3_1")
        self.btn_show_b_3_3 = QtWidgets.QPushButton(Search)
        self.btn_show_b_3_3.setGeometry(QtCore.QRect(850, 310, 41, 41))
        self.btn_show_b_3_3.setText("")
        self.btn_show_b_3_3.setObjectName("btn_show_b_3_3")
        self.btn_show_b_3_9 = QtWidgets.QPushButton(Search)
        self.btn_show_b_3_9.setGeometry(QtCore.QRect(850, 390, 41, 41))
        self.btn_show_b_3_9.setText("")
        self.btn_show_b_3_9.setObjectName("btn_show_b_3_9")
        self.btn_show_b_3_2 = QtWidgets.QPushButton(Search)
        self.btn_show_b_3_2.setGeometry(QtCore.QRect(810, 310, 41, 41))
        self.btn_show_b_3_2.setText("")
        self.btn_show_b_3_2.setObjectName("btn_show_b_3_2")
        self.btn_show_b_3_num = QtWidgets.QPushButton(Search)
        self.btn_show_b_3_num.setGeometry(QtCore.QRect(770, 440, 51, 41))
        self.btn_show_b_3_num.setText("")
        self.btn_show_b_3_num.setObjectName("btn_show_b_3_num")
        self.btn_show_b_3_5 = QtWidgets.QPushButton(Search)
        self.btn_show_b_3_5.setGeometry(QtCore.QRect(810, 350, 41, 41))
        self.btn_show_b_3_5.setText("")
        self.btn_show_b_3_5.setObjectName("btn_show_b_3_5")
        self.btn_show_b_3_4 = QtWidgets.QPushButton(Search)
        self.btn_show_b_3_4.setGeometry(QtCore.QRect(770, 350, 41, 41))
        self.btn_show_b_3_4.setText("")
        self.btn_show_b_3_4.setObjectName("btn_show_b_3_4")
        self.btn_show_b_3_6 = QtWidgets.QPushButton(Search)
        self.btn_show_b_3_6.setGeometry(QtCore.QRect(850, 350, 41, 41))
        self.btn_show_b_3_6.setText("")
        self.btn_show_b_3_6.setObjectName("btn_show_b_3_6")
        self.btn_show_b_3_8 = QtWidgets.QPushButton(Search)
        self.btn_show_b_3_8.setGeometry(QtCore.QRect(810, 390, 41, 41))
        self.btn_show_b_3_8.setText("")
        self.btn_show_b_3_8.setObjectName("btn_show_b_3_8")
        self.btn_show_f_8 = QtWidgets.QPushButton(Search)
        self.btn_show_f_8.setGeometry(QtCore.QRect(660, 180, 41, 41))
        self.btn_show_f_8.setText("")
        self.btn_show_f_8.setObjectName("btn_show_f_8")
        self.btn_show_f_9 = QtWidgets.QPushButton(Search)
        self.btn_show_f_9.setGeometry(QtCore.QRect(700, 180, 41, 41))
        self.btn_show_f_9.setText("")
        self.btn_show_f_9.setObjectName("btn_show_f_9")
        self.btn_show_f_1 = QtWidgets.QPushButton(Search)
        self.btn_show_f_1.setGeometry(QtCore.QRect(620, 100, 41, 41))
        self.btn_show_f_1.setText("")
        self.btn_show_f_1.setObjectName("btn_show_f_1")
        self.btn_show_f_2 = QtWidgets.QPushButton(Search)
        self.btn_show_f_2.setGeometry(QtCore.QRect(660, 100, 41, 41))
        self.btn_show_f_2.setText("")
        self.btn_show_f_2.setObjectName("btn_show_f_2")
        self.btn_show_f_4 = QtWidgets.QPushButton(Search)
        self.btn_show_f_4.setGeometry(QtCore.QRect(620, 140, 41, 41))
        self.btn_show_f_4.setText("")
        self.btn_show_f_4.setObjectName("btn_show_f_4")
        self.btn_show_f_7 = QtWidgets.QPushButton(Search)
        self.btn_show_f_7.setGeometry(QtCore.QRect(620, 180, 41, 41))
        self.btn_show_f_7.setText("")
        self.btn_show_f_7.setObjectName("btn_show_f_7")
        self.label_f_node = QtWidgets.QLabel(Search)
        self.label_f_node.setGeometry(QtCore.QRect(540, 180, 101, 51))
        self.label_f_node.setObjectName("label_f_node")
        self.btn_show_f_5 = QtWidgets.QPushButton(Search)
        self.btn_show_f_5.setGeometry(QtCore.QRect(660, 140, 41, 41))
        self.btn_show_f_5.setText("")
        self.btn_show_f_5.setObjectName("btn_show_f_5")
        self.btn_show_f_6 = QtWidgets.QPushButton(Search)
        self.btn_show_f_6.setGeometry(QtCore.QRect(700, 140, 41, 41))
        self.btn_show_f_6.setText("")
        self.btn_show_f_6.setObjectName("btn_show_f_6")
        self.btn_show_f_num = QtWidgets.QPushButton(Search)
        self.btn_show_f_num.setGeometry(QtCore.QRect(620, 230, 51, 41))
        self.btn_show_f_num.setText("")
        self.btn_show_f_num.setObjectName("btn_show_f_num")
        self.btn_show_f_3 = QtWidgets.QPushButton(Search)
        self.btn_show_f_3.setGeometry(QtCore.QRect(700, 100, 41, 41))
        self.btn_show_f_3.setText("")
        self.btn_show_f_3.setObjectName("btn_show_f_3")
        self.label_f_num = QtWidgets.QLabel(Search)
        self.label_f_num.setGeometry(QtCore.QRect(490, 230, 121, 51))
        self.label_f_num.setObjectName("label_f_num")
        self.btn_show_c_4 = QtWidgets.QPushButton(Search)
        self.btn_show_c_4.setGeometry(QtCore.QRect(170, 260, 61, 61))
        self.btn_show_c_4.setText("")
        self.btn_show_c_4.setObjectName("btn_show_c_4")
        self.btn_show_c_5 = QtWidgets.QPushButton(Search)
        self.btn_show_c_5.setGeometry(QtCore.QRect(230, 260, 61, 61))
        self.btn_show_c_5.setText("")
        self.btn_show_c_5.setObjectName("btn_show_c_5")
        self.btn_show_c_1 = QtWidgets.QPushButton(Search)
        self.btn_show_c_1.setGeometry(QtCore.QRect(170, 200, 61, 61))
        self.btn_show_c_1.setText("")
        self.btn_show_c_1.setObjectName("btn_show_c_1")
        self.btn_show_c_2 = QtWidgets.QPushButton(Search)
        self.btn_show_c_2.setGeometry(QtCore.QRect(230, 200, 61, 61))
        self.btn_show_c_2.setText("")
        self.btn_show_c_2.setObjectName("btn_show_c_2")
        self.btn_show_c_3 = QtWidgets.QPushButton(Search)
        self.btn_show_c_3.setGeometry(QtCore.QRect(290, 200, 61, 61))
        self.btn_show_c_3.setText("")
        self.btn_show_c_3.setObjectName("btn_show_c_3")
        self.btn_show_c_6 = QtWidgets.QPushButton(Search)
        self.btn_show_c_6.setGeometry(QtCore.QRect(290, 260, 61, 61))
        self.btn_show_c_6.setText("")
        self.btn_show_c_6.setObjectName("btn_show_c_6")
        self.btn_show_c_9 = QtWidgets.QPushButton(Search)
        self.btn_show_c_9.setGeometry(QtCore.QRect(290, 320, 61, 61))
        self.btn_show_c_9.setText("")
        self.btn_show_c_9.setObjectName("btn_show_c_9")
        self.btn_show_c_8 = QtWidgets.QPushButton(Search)
        self.btn_show_c_8.setGeometry(QtCore.QRect(230, 320, 61, 61))
        self.btn_show_c_8.setText("")
        self.btn_show_c_8.setObjectName("btn_show_c_8")
        self.btn_show_c_7 = QtWidgets.QPushButton(Search)
        self.btn_show_c_7.setGeometry(QtCore.QRect(170, 320, 61, 61))
        self.btn_show_c_7.setText("")
        self.btn_show_c_7.setObjectName("btn_show_c_7")
        self.label_open = QtWidgets.QLabel(Search)
        self.label_open.setGeometry(QtCore.QRect(110, 700, 101, 51))
        self.label_open.setObjectName("label_open")
        self.label_close = QtWidgets.QLabel(Search)
        self.label_close.setGeometry(QtCore.QRect(110, 750, 101, 51))
        self.label_close.setObjectName("label_close")
        self.btn_show_c_loss = QtWidgets.QPushButton(Search)
        self.btn_show_c_loss.setGeometry(QtCore.QRect(290, 400, 61, 61))
        self.btn_show_c_loss.setText("")
        self.btn_show_c_loss.setObjectName("btn_show_c_loss")
        self.btn_show_f_loss = QtWidgets.QPushButton(Search)
        self.btn_show_f_loss.setGeometry(QtCore.QRect(690, 230, 51, 41))
        self.btn_show_f_loss.setText("")
        self.btn_show_f_loss.setObjectName("btn_show_f_loss")
        self.btn_show_b_1_loss = QtWidgets.QPushButton(Search)
        self.btn_show_b_1_loss.setGeometry(QtCore.QRect(540, 440, 51, 41))
        self.btn_show_b_1_loss.setText("")
        self.btn_show_b_1_loss.setObjectName("btn_show_b_1_loss")
        self.btn_show_b_2_loss = QtWidgets.QPushButton(Search)
        self.btn_show_b_2_loss.setGeometry(QtCore.QRect(690, 440, 51, 41))
        self.btn_show_b_2_loss.setText("")
        self.btn_show_b_2_loss.setObjectName("btn_show_b_2_loss")
        self.btn_show_b_3_loss = QtWidgets.QPushButton(Search)
        self.btn_show_b_3_loss.setGeometry(QtCore.QRect(840, 440, 51, 41))
        self.btn_show_b_3_loss.setText("")
        self.btn_show_b_3_loss.setObjectName("btn_show_b_3_loss")
        self.btn_show_e_1_1 = QtWidgets.QPushButton(Search)
        self.btn_show_e_1_1.setGeometry(QtCore.QRect(200, 510, 41, 41))
        self.btn_show_e_1_1.setText("")
        self.btn_show_e_1_1.setObjectName("btn_show_e_1_1")
        self.btn_show_e_2_2 = QtWidgets.QPushButton(Search)
        self.btn_show_e_2_2.setGeometry(QtCore.QRect(410, 510, 41, 41))
        self.btn_show_e_2_2.setText("")
        self.btn_show_e_2_2.setObjectName("btn_show_e_2_2")
        self.btn_show_e_3_loss = QtWidgets.QPushButton(Search)
        self.btn_show_e_3_loss.setGeometry(QtCore.QRect(610, 640, 51, 41))
        self.btn_show_e_3_loss.setText("")
        self.btn_show_e_3_loss.setObjectName("btn_show_e_3_loss")
        self.btn_show_e_1_6 = QtWidgets.QPushButton(Search)
        self.btn_show_e_1_6.setGeometry(QtCore.QRect(280, 550, 41, 41))
        self.btn_show_e_1_6.setText("")
        self.btn_show_e_1_6.setObjectName("btn_show_e_1_6")
        self.btn_show_e_2_3 = QtWidgets.QPushButton(Search)
        self.btn_show_e_2_3.setGeometry(QtCore.QRect(450, 510, 41, 41))
        self.btn_show_e_2_3.setText("")
        self.btn_show_e_2_3.setObjectName("btn_show_e_2_3")
        self.btn_show_e_1_9 = QtWidgets.QPushButton(Search)
        self.btn_show_e_1_9.setGeometry(QtCore.QRect(280, 590, 41, 41))
        self.btn_show_e_1_9.setText("")
        self.btn_show_e_1_9.setObjectName("btn_show_e_1_9")
        self.btn_show_e_3_1 = QtWidgets.QPushButton(Search)
        self.btn_show_e_3_1.setGeometry(QtCore.QRect(540, 510, 41, 41))
        self.btn_show_e_3_1.setText("")
        self.btn_show_e_3_1.setObjectName("btn_show_e_3_1")
        self.btn_show_e_2_5 = QtWidgets.QPushButton(Search)
        self.btn_show_e_2_5.setGeometry(QtCore.QRect(410, 550, 41, 41))
        self.btn_show_e_2_5.setText("")
        self.btn_show_e_2_5.setObjectName("btn_show_e_2_5")
        self.btn_show_e_1_2 = QtWidgets.QPushButton(Search)
        self.btn_show_e_1_2.setGeometry(QtCore.QRect(240, 510, 41, 41))
        self.btn_show_e_1_2.setText("")
        self.btn_show_e_1_2.setObjectName("btn_show_e_1_2")
        self.label_e_num = QtWidgets.QLabel(Search)
        self.label_e_num.setGeometry(QtCore.QRect(70, 640, 121, 51))
        self.label_e_num.setObjectName("label_e_num")
        self.btn_show_e_2_8 = QtWidgets.QPushButton(Search)
        self.btn_show_e_2_8.setGeometry(QtCore.QRect(410, 590, 41, 41))
        self.btn_show_e_2_8.setText("")
        self.btn_show_e_2_8.setObjectName("btn_show_e_2_8")
        self.btn_show_e_2_7 = QtWidgets.QPushButton(Search)
        self.btn_show_e_2_7.setGeometry(QtCore.QRect(370, 590, 41, 41))
        self.btn_show_e_2_7.setText("")
        self.btn_show_e_2_7.setObjectName("btn_show_e_2_7")
        self.btn_show_e_3_7 = QtWidgets.QPushButton(Search)
        self.btn_show_e_3_7.setGeometry(QtCore.QRect(540, 590, 41, 41))
        self.btn_show_e_3_7.setText("")
        self.btn_show_e_3_7.setObjectName("btn_show_e_3_7")
        self.btn_show_e_3_9 = QtWidgets.QPushButton(Search)
        self.btn_show_e_3_9.setGeometry(QtCore.QRect(620, 590, 41, 41))
        self.btn_show_e_3_9.setText("")
        self.btn_show_e_3_9.setObjectName("btn_show_e_3_9")
        self.btn_show_e_2_6 = QtWidgets.QPushButton(Search)
        self.btn_show_e_2_6.setGeometry(QtCore.QRect(450, 550, 41, 41))
        self.btn_show_e_2_6.setText("")
        self.btn_show_e_2_6.setObjectName("btn_show_e_2_6")
        self.btn_show_e_3_6 = QtWidgets.QPushButton(Search)
        self.btn_show_e_3_6.setGeometry(QtCore.QRect(620, 550, 41, 41))
        self.btn_show_e_3_6.setText("")
        self.btn_show_e_3_6.setObjectName("btn_show_e_3_6")
        self.btn_show_e_1_3 = QtWidgets.QPushButton(Search)
        self.btn_show_e_1_3.setGeometry(QtCore.QRect(280, 510, 41, 41))
        self.btn_show_e_1_3.setText("")
        self.btn_show_e_1_3.setObjectName("btn_show_e_1_3")
        self.btn_show_e_1_4 = QtWidgets.QPushButton(Search)
        self.btn_show_e_1_4.setGeometry(QtCore.QRect(200, 550, 41, 41))
        self.btn_show_e_1_4.setText("")
        self.btn_show_e_1_4.setObjectName("btn_show_e_1_4")
        self.btn_show_e_2_num = QtWidgets.QPushButton(Search)
        self.btn_show_e_2_num.setGeometry(QtCore.QRect(370, 640, 51, 41))
        self.btn_show_e_2_num.setText("")
        self.btn_show_e_2_num.setObjectName("btn_show_e_2_num")
        self.btn_show_e_3_4 = QtWidgets.QPushButton(Search)
        self.btn_show_e_3_4.setGeometry(QtCore.QRect(540, 550, 41, 41))
        self.btn_show_e_3_4.setText("")
        self.btn_show_e_3_4.setObjectName("btn_show_e_3_4")
        self.btn_show_e_1_5 = QtWidgets.QPushButton(Search)
        self.btn_show_e_1_5.setGeometry(QtCore.QRect(240, 550, 41, 41))
        self.btn_show_e_1_5.setText("")
        self.btn_show_e_1_5.setObjectName("btn_show_e_1_5")
        self.btn_show_e_2_4 = QtWidgets.QPushButton(Search)
        self.btn_show_e_2_4.setGeometry(QtCore.QRect(370, 550, 41, 41))
        self.btn_show_e_2_4.setText("")
        self.btn_show_e_2_4.setObjectName("btn_show_e_2_4")
        self.btn_show_e_3_5 = QtWidgets.QPushButton(Search)
        self.btn_show_e_3_5.setGeometry(QtCore.QRect(580, 550, 41, 41))
        self.btn_show_e_3_5.setText("")
        self.btn_show_e_3_5.setObjectName("btn_show_e_3_5")
        self.btn_show_e_3_num = QtWidgets.QPushButton(Search)
        self.btn_show_e_3_num.setGeometry(QtCore.QRect(540, 640, 51, 41))
        self.btn_show_e_3_num.setText("")
        self.btn_show_e_3_num.setObjectName("btn_show_e_3_num")
        self.btn_show_e_1_7 = QtWidgets.QPushButton(Search)
        self.btn_show_e_1_7.setGeometry(QtCore.QRect(200, 590, 41, 41))
        self.btn_show_e_1_7.setText("")
        self.btn_show_e_1_7.setObjectName("btn_show_e_1_7")
        self.btn_show_e_1_8 = QtWidgets.QPushButton(Search)
        self.btn_show_e_1_8.setGeometry(QtCore.QRect(240, 590, 41, 41))
        self.btn_show_e_1_8.setText("")
        self.btn_show_e_1_8.setObjectName("btn_show_e_1_8")
        self.btn_show_e_3_3 = QtWidgets.QPushButton(Search)
        self.btn_show_e_3_3.setGeometry(QtCore.QRect(620, 510, 41, 41))
        self.btn_show_e_3_3.setText("")
        self.btn_show_e_3_3.setObjectName("btn_show_e_3_3")
        self.label_e_node = QtWidgets.QLabel(Search)
        self.label_e_node.setGeometry(QtCore.QRect(100, 590, 101, 51))
        self.label_e_node.setObjectName("label_e_node")
        self.btn_show_e_1_loss = QtWidgets.QPushButton(Search)
        self.btn_show_e_1_loss.setGeometry(QtCore.QRect(270, 640, 51, 41))
        self.btn_show_e_1_loss.setText("")
        self.btn_show_e_1_loss.setObjectName("btn_show_e_1_loss")
        self.btn_show_e_1_num = QtWidgets.QPushButton(Search)
        self.btn_show_e_1_num.setGeometry(QtCore.QRect(200, 640, 51, 41))
        self.btn_show_e_1_num.setText("")
        self.btn_show_e_1_num.setObjectName("btn_show_e_1_num")
        self.btn_show_e_2_1 = QtWidgets.QPushButton(Search)
        self.btn_show_e_2_1.setGeometry(QtCore.QRect(370, 510, 41, 41))
        self.btn_show_e_2_1.setText("")
        self.btn_show_e_2_1.setObjectName("btn_show_e_2_1")
        self.btn_show_e_2_loss = QtWidgets.QPushButton(Search)
        self.btn_show_e_2_loss.setGeometry(QtCore.QRect(440, 640, 51, 41))
        self.btn_show_e_2_loss.setText("")
        self.btn_show_e_2_loss.setObjectName("btn_show_e_2_loss")
        self.btn_show_e_3_8 = QtWidgets.QPushButton(Search)
        self.btn_show_e_3_8.setGeometry(QtCore.QRect(580, 590, 41, 41))
        self.btn_show_e_3_8.setText("")
        self.btn_show_e_3_8.setObjectName("btn_show_e_3_8")
        self.btn_show_e_2_9 = QtWidgets.QPushButton(Search)
        self.btn_show_e_2_9.setGeometry(QtCore.QRect(450, 590, 41, 41))
        self.btn_show_e_2_9.setText("")
        self.btn_show_e_2_9.setObjectName("btn_show_e_2_9")
        self.btn_show_e_3_2 = QtWidgets.QPushButton(Search)
        self.btn_show_e_3_2.setGeometry(QtCore.QRect(580, 510, 41, 41))
        self.btn_show_e_3_2.setText("")
        self.btn_show_e_3_2.setObjectName("btn_show_e_3_2")
        self.btn_show_e_4_5 = QtWidgets.QPushButton(Search)
        self.btn_show_e_4_5.setGeometry(QtCore.QRect(750, 550, 41, 41))
        self.btn_show_e_4_5.setText("")
        self.btn_show_e_4_5.setObjectName("btn_show_e_4_5")
        self.btn_show_e_4_loss = QtWidgets.QPushButton(Search)
        self.btn_show_e_4_loss.setGeometry(QtCore.QRect(780, 640, 51, 41))
        self.btn_show_e_4_loss.setText("")
        self.btn_show_e_4_loss.setObjectName("btn_show_e_4_loss")
        self.btn_show_e_4_1 = QtWidgets.QPushButton(Search)
        self.btn_show_e_4_1.setGeometry(QtCore.QRect(710, 510, 41, 41))
        self.btn_show_e_4_1.setText("")
        self.btn_show_e_4_1.setObjectName("btn_show_e_4_1")
        self.btn_show_e_4_num = QtWidgets.QPushButton(Search)
        self.btn_show_e_4_num.setGeometry(QtCore.QRect(710, 640, 51, 41))
        self.btn_show_e_4_num.setText("")
        self.btn_show_e_4_num.setObjectName("btn_show_e_4_num")
        self.btn_show_e_4_6 = QtWidgets.QPushButton(Search)
        self.btn_show_e_4_6.setGeometry(QtCore.QRect(790, 550, 41, 41))
        self.btn_show_e_4_6.setText("")
        self.btn_show_e_4_6.setObjectName("btn_show_e_4_6")
        self.btn_show_e_4_4 = QtWidgets.QPushButton(Search)
        self.btn_show_e_4_4.setGeometry(QtCore.QRect(710, 550, 41, 41))
        self.btn_show_e_4_4.setText("")
        self.btn_show_e_4_4.setObjectName("btn_show_e_4_4")
        self.btn_show_e_4_2 = QtWidgets.QPushButton(Search)
        self.btn_show_e_4_2.setGeometry(QtCore.QRect(750, 510, 41, 41))
        self.btn_show_e_4_2.setText("")
        self.btn_show_e_4_2.setObjectName("btn_show_e_4_2")
        self.btn_show_e_4_9 = QtWidgets.QPushButton(Search)
        self.btn_show_e_4_9.setGeometry(QtCore.QRect(790, 590, 41, 41))
        self.btn_show_e_4_9.setText("")
        self.btn_show_e_4_9.setObjectName("btn_show_e_4_9")
        self.btn_show_e_4_3 = QtWidgets.QPushButton(Search)
        self.btn_show_e_4_3.setGeometry(QtCore.QRect(790, 510, 41, 41))
        self.btn_show_e_4_3.setText("")
        self.btn_show_e_4_3.setObjectName("btn_show_e_4_3")
        self.btn_show_e_4_7 = QtWidgets.QPushButton(Search)
        self.btn_show_e_4_7.setGeometry(QtCore.QRect(710, 590, 41, 41))
        self.btn_show_e_4_7.setText("")
        self.btn_show_e_4_7.setObjectName("btn_show_e_4_7")
        self.btn_show_e_4_8 = QtWidgets.QPushButton(Search)
        self.btn_show_e_4_8.setGeometry(QtCore.QRect(750, 590, 41, 41))
        self.btn_show_e_4_8.setText("")
        self.btn_show_e_4_8.setObjectName("btn_show_e_4_8")
        self.label_efficiency = QtWidgets.QLabel(Search)
        self.label_efficiency.setGeometry(QtCore.QRect(140, 800, 101, 51))
        self.label_efficiency.setObjectName("label_efficiency")
        self.btn_show_efficiency = QtWidgets.QPushButton(Search)
        self.btn_show_efficiency.setGeometry(QtCore.QRect(200, 810, 111, 41))
        self.btn_show_efficiency.setText("")
        self.btn_show_efficiency.setObjectName("btn_show_efficiency")
        self.lineEdit_open = QtWidgets.QLineEdit(Search)
        self.lineEdit_open.setGeometry(QtCore.QRect(200, 700, 671, 41))
        self.lineEdit_open.setObjectName("lineEdit_open")
        self.lineEdit_close = QtWidgets.QLineEdit(Search)
        self.lineEdit_close.setGeometry(QtCore.QRect(200, 750, 671, 41))
        self.lineEdit_close.setObjectName("lineEdit_close")
        self.btn_first_step = QtWidgets.QPushButton(Search)
        self.btn_first_step.setGeometry(QtCore.QRect(330, 810, 71, 41))
        self.btn_first_step.setObjectName("btn_first_step")
        self.btn_last_step = QtWidgets.QPushButton(Search)
        self.btn_last_step.setGeometry(QtCore.QRect(660, 810, 71, 41))
        self.btn_last_step.setObjectName("btn_last_step")
        self.label_dm = QtWidgets.QLabel(Search)
        self.label_dm.setGeometry(QtCore.QRect(120, 150, 101, 51))
        self.label_dm.setObjectName("label_dm")
        self.comboBox_dm = QtWidgets.QComboBox(Search)
        self.comboBox_dm.setGeometry(QtCore.QRect(210, 150, 201, 41))
        self.comboBox_dm.setObjectName("comboBox_dm")
        self.label_heuristic = QtWidgets.QLabel(Search)
        self.label_heuristic.setGeometry(QtCore.QRect(80, 150, 121, 51))
        self.label_heuristic.setObjectName("label_heuristic")
        self.comboBox_heuristic = QtWidgets.QComboBox(Search)
        self.comboBox_heuristic.setGeometry(QtCore.QRect(210, 150, 201, 41))
        self.comboBox_heuristic.setObjectName("comboBox_heuristic")

        self.retranslateUi(Search)
        QtCore.QMetaObject.connectSlotsByName(Search)

    def retranslateUi(self, Search):
        _translate = QtCore.QCoreApplication.translate
        Search.setWindowTitle(_translate("Search", "搜索实验"))
        self.btn_previous_step.setText(_translate("Search", "上一步"))
        self.btn_play.setText(_translate("Search", "播放"))
        self.label_frame_rate.setText(_translate("Search", "帧速："))
        self.label_initial_state.setText(_translate("Search", "初始状态："))
        self.label_algorithm.setText(_translate("Search", "算法选择："))
        self.btn_next_step.setText(_translate("Search", "下一步"))
        self.btn_start.setText(_translate("Search", "开始演示"))
        self.label_target.setText(_translate("Search", "目标状态："))
        self.btn_formatting.setText(_translate("Search", "格式化"))
        self.label_c_node.setText(_translate("Search", "当前节点："))
        self.label_c_num.setText(_translate("Search", "编号和损失值："))
        self.label_b_node.setText(_translate("Search", "兄弟节点："))
        self.label_b_num.setText(_translate("Search", "编号和损失值："))
        self.label_f_node.setText(_translate("Search", "父节点："))
        self.label_f_num.setText(_translate("Search", "编号和损失值："))
        self.label_open.setText(_translate("Search", "open表："))
        self.label_close.setText(_translate("Search", "close表："))
        self.label_e_num.setText(_translate("Search", "编号和损失值："))
        self.label_e_node.setText(_translate("Search", "扩展节点："))
        self.label_efficiency.setText(_translate("Search", "效率："))
        self.btn_first_step.setText(_translate("Search", "首步"))
        self.btn_last_step.setText(_translate("Search", "尾步"))
        self.label_dm.setText(_translate("Search", "最大深度："))
        self.label_heuristic.setText(_translate("Search", "启发函数选择："))

